[package]
name = "bms_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.15.0"
num = "0.4.1"
num-traits = "0.2.17"
ordered-float = "4.2.0"
regex = "1.10.2"
unicase = "2.7.0"
